logging:
  level:
    ROOT: INFO
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: 3450Di@2
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create

spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/data_jpa?createDatabaseIfNotExist=true
    username: root
    password: 3450Di@2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true


#ddl-auto: create-drop
#          create
#          none
#          update   compare with the java entity and table
#          validate