logging:
  level:
    ROOT: INFO
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: 3450Di@2
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data_jpa?createDatabaseIfNotExist=true
    username: root
    password: 3450Di@2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
